### ISSUE TITLE
Recipe setup: Location the files are saved is not clear + When loading an existing file no method to define location of saving

### ISSUE THREAD

**Issue by ruizhi-wang** [ruizhi-wang/Perlis_v0#21]
1) Saving file:
When saving file, it is not evident for the user that he has to provide a name that is then used for three files that are then generated

2) Loading:
When loading a recipe and then running it, the new files are saved with the same name in the same location.

**Comment by cbbrstn** [comment]
when is the user creating a new "path"?

**Comment by lukasvasadi** [comment]
To correct this issue, I changed the landing window "Setup new experiment" button to automatically prompt user to create file save directory. Then the setup window is opened, where the user has the option to load an existing recipe. The data will be written into the setup table and a new recipe file created at "Continue". In my opinion, this clears up most of the confusion and also eliminates the common "filename_recipe_recipe.txt" bug.

**Comment by cbbrstn** [comment]
Sounds good to me! Good work!
