### ISSUE TITLE
Close button does not work on recipe create or load prompt

### ISSUE THREAD

**Issue by cbbrstn** [ruizhi-wang/Perlis_v0#6]
![image](https://user-images.githubusercontent.com/23585684/68014790-c3ae9700-fc90-11e9-9a55-0e9b1cc97ccf.png)

Close button does not work (top left corner)
Better even would be to add a cancel button to the prompt.

**Comment by lukasvasadi** [comment]
Added three lines to restore default button behaviors, such as the close action. Did not add a cancel button; should consider in the future...
