### ISSUE TITLE
What's the text editor for?

### ISSUE THREAD

**Issue by cbbrstn** [ruizhi-wang/Perlis_v0#7]
If it doesn't serve a substantial need we should kill it as it dstracts.

![image](https://user-images.githubusercontent.com/23585684/68015006-636c2500-fc91-11e9-8074-d4d844fcd8a6.png)

**Comment by lukasvasadi** [comment]
It's original purpose was to make it easier for us to modify recipe text files, i.e., writing directly through the text editor vs. the recipe table, but I agree that it would probably confuse the customer...

**Comment by cbbrstn** [comment]
Ok, thanks for the clarification. I have deactivated the feature ('button') for now. We can re-introduce again later if we see the need again.
